//! Parity gate for the hand-ported next-track champion (src/champion.rs) vs the
//! Python reference `seq_blend.py predict` over the promoted champion dir.
//!
//! Fixtures are regenerated by:
//!   ../spotify-next-track/predictors/.venv/bin/python tools/build_champion_parity.py
//! and the baked model by:
//!   server/.venv/bin/python tools/build_champion.py
//!
//! The champion is deterministic, so the top-10 item indices must match the
//! Python reference EXACTLY (set + order); the raw GRU predicted-latent must
//! match to ~1e-4.

use serde_json::Value;
use std::fs;
use std::path::PathBuf;
use worker_core::champion::Champion;

fn app_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn load_champion() -> Champion {
    let bytes = fs::read(app_root().join("public/data/champion.bin"))
        .expect("read public/data/champion.bin (run tools/build_champion.py)");
    Champion::parse(&bytes).expect("parse champion.bin")
}

fn fixture() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/champion_parity.json");
    serde_json::from_str(&fs::read_to_string(path).expect("read champion_parity.json")).unwrap()
}

fn as_usize_vec(v: &Value) -> Vec<usize> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect()
}

#[test]
fn topk_matches_python_reference() {
    let champ = load_champion();
    let fx = fixture();
    let k = fx["k"].as_u64().unwrap() as usize;

    let mut n_cases = 0;
    for case in fx["prefixes"].as_array().unwrap() {
        let prefix = as_usize_vec(&case["prefix"]);
        let expected = as_usize_vec(&case["top_k_ids"]);
        let got: Vec<usize> = champ.blend_rank(&prefix, k).into_iter().map(|(i, _)| i).collect();
        assert_eq!(
            got, expected,
            "top-{k} mismatch for prefix {prefix:?}\n  rust:   {got:?}\n  python: {expected:?}"
        );
        n_cases += 1;
    }
    assert!(n_cases >= 5, "expected >= 5 parity cases, got {n_cases}");
    eprintln!("champion top-{k} parity: {n_cases} prefixes matched exactly");
}

#[test]
fn gru_latent_matches_python_reference() {
    let champ = load_champion();
    let fx = fixture();

    let mut worst = 0.0f64;
    for case in fx["latent_checks"].as_array().unwrap() {
        let prefix = as_usize_vec(&case["prefix"]);
        let expected: Vec<f64> = case["pred_latent"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_f64().unwrap())
            .collect();
        let got = champ.predict_next_latent(&prefix);
        assert_eq!(got.len(), expected.len(), "latent dim");
        let mut max_abs = 0.0f64;
        for (g, e) in got.iter().zip(expected.iter()) {
            max_abs = max_abs.max((*g as f64 - *e).abs());
        }
        eprintln!("prefix {prefix:?}: GRU latent max-abs-diff {max_abs:.3e}");
        worst = worst.max(max_abs);
    }
    assert!(worst < 1e-4, "GRU latent max-abs-diff {worst:.3e} exceeds 1e-4");
}
