//! Fidelity gate for the hand-ported rotation-fit scorer (src/scorer.rs) vs the
//! offline ONNX path. Fixtures come from tools/export_scorer.py, which itself
//! asserts its NumPy reference forward matches onnxruntime within 1e-5 — so this
//! test transitively guarantees the Rust port reproduces the real ONNX model.
//!
//! `scorer.bin` + `scorer_parity.json` are regenerated by:
//!   server/.venv/bin/python tools/export_scorer.py

use serde_json::Value;
use std::fs;
use std::path::PathBuf;
use worker_core::scorer::Scorer;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn load_scorer() -> Scorer {
    let bytes = fs::read(fixtures_dir().join("scorer.bin")).expect("read scorer.bin");
    Scorer::parse(&bytes).expect("parse scorer.bin")
}

#[test]
fn featurize_matches_onnx_featurizer() {
    let sc = load_scorer();
    let fx: Value = serde_json::from_str(
        &fs::read_to_string(fixtures_dir().join("scorer_parity.json")).expect("read fixture"),
    )
    .unwrap();

    let mut max_diff = 0.0f32;
    for case in fx["cases"].as_array().unwrap() {
        let latent: Vec<f32> = case["latent"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let expected: Vec<f32> = case["feats"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let got = sc.featurize(&latent, &case["meta"]).expect("featurize");
        assert_eq!(got.len(), expected.len(), "feature length");
        for (g, e) in got.iter().zip(expected.iter()) {
            max_diff = max_diff.max((g - e).abs());
        }
    }
    assert!(max_diff < 1e-5, "featurize max abs diff {max_diff} exceeds 1e-5");
}

#[test]
fn score_matches_onnx_output() {
    let sc = load_scorer();
    let fx: Value = serde_json::from_str(
        &fs::read_to_string(fixtures_dir().join("scorer_parity.json")).expect("read fixture"),
    )
    .unwrap();

    let mut max_diff = 0.0f32;
    for case in fx["cases"].as_array().unwrap() {
        let latent: Vec<f32> = case["latent"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let expected = case["raw"].as_f64().unwrap() as f32;
        let got = sc.score(&latent, &case["meta"]).expect("score");
        max_diff = max_diff.max((got - expected).abs());
    }
    assert!(max_diff < 1e-4, "score max abs diff {max_diff} exceeds 1e-4");
}

#[test]
fn rejects_bad_magic() {
    assert!(Scorer::parse(b"XXXX....").is_err());
}
